version: "2"                
services: 
  redis:
    image: redis:4.0
    container_name: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}    
    volumes:
      - "./docker/redis/:/data/"    
  solve:                      
    build: 
      context: ./solve
      dockerfile: Dockerfile
      args:
        INDEX_URL: https://mirrors.aliyun.com/pypi/simple/ 
        TRUSTED_HOST: mirrors.aliyun.com 
    image: solve:${VERSION}
    depends_on:                          
      - redis
    volumes:
      - "${DATA_PATH_LOCAL}:${DATA_PATH_DOCKER}"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      AES_KEY: ${AES_KEY}
    privileged: true
  solve-backend:                      
    build: 
      context: ./solve-backend
      dockerfile: Dockerfile
      args:
        INDEX_URL: https://mirrors.aliyun.com/pypi/simple/ 
        TRUSTED_HOST: mirrors.aliyun.com 
    image: solve-backend:${VERSION}
    depends_on:                          
      - redis
    volumes:
      - "${DATA_PATH_LOCAL}:${DATA_PATH_DOCKER}"
      - "./docker/solve-backend/db.sqlite3:/data/solve-backend/db.sqlite3"
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      BACKEND_NAME: ${BACKEND_NAME}
      DATA_PATH: ${DATA_PATH_DOCKER}
    privileged: true
  solve-frontend:                       
    build: 
      context: ./solve-frontend
      dockerfile: Dockerfile
      args:
        REGISTRY: https://registry.npm.taobao.org/
    image: solve-frontend:${VERSION}     
    depends_on:             
      - solve-backend                  
    ports:
      - "${FRONTEND_PORT}:8080"      
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_NAME: ${BACKEND_NAME}
    privileged: true 