version: "2"                
services: 
  redis:                    
    build: 
      context: ./docker/redis
      dockerfile: Dockerfile
    image: solve-redis:latest
    ports:
      - "6379:6379"
  solve:                      
    build: 
      context: ./solve
      dockerfile: Dockerfile
      args:
        INDEX_URL: https://mirrors.aliyun.com/pypi/simple/ 
        TRUSTED_HOST: mirrors.aliyun.com 
    image: solve:0.14.4
    depends_on:                          
      - redis
    volumes:
      - "/tmp:/tmp"
    environment:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
  solve-backend:                      
    build: 
      context: ./solve-backend
      dockerfile: Dockerfile
      args:
        INDEX_URL: https://mirrors.aliyun.com/pypi/simple/ 
        TRUSTED_HOST: mirrors.aliyun.com 
    image: solve-backend:0.14.4
    depends_on:                          
      - redis
    volumes:
      - "/tmp:/tmp"
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
  solve-frontend:                       
    build: 
      context: ./solve-frontend
      dockerfile: Dockerfile
      args:
        REGISTRY: https://registry.npm.taobao.org/
    image: solve-frontend:0.14.4      
    depends_on:             
      - solve-backend                  
    ports:
      - "8080:8080"      
    environment:
      BACKEND_HOST: 127.0.0.1
      BACKEND_PORT: 8000      
