version: "2"                
services: 
  redis:
    image: redis:4.0
    container_name: redis
    restart: always
    command: redis-server --requirepass my_redis_passwd    
    volumes:
      - "./docker/redis/dump.rdb:/data"    
  solve:                      
    build: 
      context: ./solve
      dockerfile: Dockerfile
      args:
        INDEX_URL: https://mirrors.aliyun.com/pypi/simple/ 
        TRUSTED_HOST: mirrors.aliyun.com 
    image: solve:${VERSION}
    depends_on:                          
      - redis
    volumes:
      - "/tmp:/tmp"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: my_redis_passwd
  solve-backend:                      
    build: 
      context: ./solve-backend
      dockerfile: Dockerfile
      args:
        INDEX_URL: https://mirrors.aliyun.com/pypi/simple/ 
        TRUSTED_HOST: mirrors.aliyun.com 
    image: solve-backend:${VERSION}
    depends_on:                          
      - redis
    volumes:
      - "/tmp:/tmp"
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: my_redis_passwd
  solve-frontend:                       
    build: 
      context: ./solve-frontend
      dockerfile: Dockerfile
      args:
        REGISTRY: https://registry.npm.taobao.org/
    image: solve-frontend:${VERSION}     
    depends_on:             
      - solve-backend                  
    ports:
      - "8080:8080"      
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: 8000      
